# Generated by Django 3.0.4 on 2020-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user_image',
            field=models.ImageField(default='main/images/user_image.jpg', upload_to=None),
        ),
    ]
