# Generated by Django 3.0.4 on 2020-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200309_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Information'),
        ),
    ]
