# Generated by Django 3.0.4 on 2020-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resume_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='extra_info',
            field=models.TextField(blank=True, default='No Information', null=True, verbose_name='Extra Information'),
        ),
    ]
