# Generated by Django 3.0.4 on 2020-03-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200310_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_image',
            field=models.ImageField(default='main/images/user_image.jpg', height_field='picture_height', max_length=255, upload_to='images/%Y/%m/%d/', width_field='picture_width'),
        ),
    ]
