# Generated by Django 3.0.4 on 2020-03-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200310_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_image',
            field=models.ImageField(default='/images/user_image.jpg', max_length=255, upload_to='images'),
        ),
    ]
