# Generated by Django 3.0.4 on 2020-03-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200312_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user_job',
            field=models.CharField(blank=True, default='Programmer', max_length=250, null=True),
        ),
    ]
